<?xml version="1.0"?>
<package format="3">
  <name>assignment_6_2_1_ImageToolsTest</name>
  <version>0.0.1</version>
  <description>A package for testing image tools</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>cam2image_vm2ros</depend>
  <depend>image_tools</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>